import type { ScreenConfig } from "./types";

export const screens: ScreenConfig[] = [
  // 1. Name
  {
    id: "name",
    type: "text",
    title: "What's your name?",
    subtitle: "Let's start with the basics",
    field: "fullName",
    extraFields: ["preferredName"],
    required: true,
  },
  // 2. Contact
  {
    id: "contact",
    type: "text-pills",
    title: "How can we reach you?",
    subtitle: "We'll only contact you through your preferred methods",
    field: "email",
    extraFields: ["phone", "preferredContactMethods"],
    required: true,
    options: [
      { id: "email", label: "Email" },
      { id: "text", label: "Text" },
      { id: "whatsapp", label: "WhatsApp" },
    ],
  },
  // 3. Location
  {
    id: "location",
    type: "autocomplete",
    title: "Where are you based?",
    field: "currentLocation",
    extraFields: ["isNomadic", "nomadicBaseLocation"],
    required: true,
  },
  // 4. Birth Info
  {
    id: "birth-info",
    type: "birth-info",
    title: "Birth information",
    subtitle: "For Human Design, Astrology, Gene Keys",
    field: "birthDate",
    extraFields: ["birthTime", "birthLocation", "unknownBirthTime"],
    required: true,
  },
  // 5. Your Role
  {
    id: "your-role",
    type: "multi-select",
    title: "What roles do you identify with?",
    subtitle: "Select all that resonate",
    field: "identityRoles",
    extraFields: ["primaryRole"],
    hasOther: true,
    otherPlaceholder: "Describe your role...",
    otherField: "identityRolesOther",
    required: true,
    options: [
      { id: "breathwork", label: "Breathwork practitioner" },
      { id: "meditation", label: "Meditation guide" },
      { id: "somatic", label: "Somatic/bodywork" },
      { id: "yoga", label: "Yoga instructor" },
      { id: "sound-healer", label: "Sound healer" },
      { id: "energy-worker", label: "Energy worker" },
      { id: "medicine-guide", label: "Medicine guide" },
      { id: "community-builder", label: "Community builder" },
      { id: "entrepreneur", label: "Conscious entrepreneur" },
      { id: "farmer", label: "Regenerative farmer" },
      { id: "event-organizer", label: "Event organizer" },
      { id: "musician", label: "Musician/DJ/producer" },
      { id: "visual-artist", label: "Visual artist/designer" },
      { id: "photographer", label: "Photographer/videographer" },
      { id: "content-creator", label: "Content creator" },
      { id: "developer", label: "Developer/technologist" },
      { id: "land-developer", label: "Land developer" },
      { id: "podcaster", label: "Podcaster" },
    ],
  },
  // 6. New Earth
  {
    id: "new-earth",
    type: "multi-select",
    title: "What does New Earth mean to you?",
    subtitle: "Select at least 2 that resonate",
    field: "newEarthMeaning",
    minSelect: 2,
    hasOther: true,
    otherPlaceholder: "In your own words...",
    otherField: "newEarthMeaningOther",
    required: true,
    options: [
      { id: "harmony", label: "Living in harmony with nature and each other" },
      { id: "new-systems", label: "Building systems outside the old paradigm" },
      { id: "sovereignty", label: "Sovereignty over body, mind, and spirit" },
      { id: "authenticity", label: "Community rooted in authenticity and love" },
      { id: "regen-economics", label: "Regenerative economics and gift economy" },
      { id: "healing-trauma", label: "Healing intergenerational trauma collectively" },
      { id: "tech-service", label: "Technology in service of humanity, not control" },
      { id: "sacred-land", label: "Sacred relationship with the land" },
      { id: "co-create", label: "Co-creating a world that works for everyone" },
      { id: "indigenous-wisdom", label: "Returning to indigenous wisdom and practices" },
      { id: "conscious-evolution", label: "Conscious evolution of human potential" },
      { id: "decentralized", label: "Decentralized, self-governing communities" },
    ],
  },
  // 7. Intention
  {
    id: "intention",
    type: "multi-select",
    title: "What's your primary intention for joining?",
    subtitle: "Select all that resonate",
    field: "primaryIntention",
    hasOther: true,
    otherPlaceholder: "Your intention...",
    otherField: "primaryIntentionOther",
    required: true,
    options: [
      { id: "soul-family", label: "Find my soul family and deep connection" },
      { id: "inner-work", label: "Do my inner work alongside others" },
      { id: "contribute", label: "Contribute my gifts and be of service" },
      { id: "learn", label: "Learn tools for conscious living" },
      { id: "collaborate", label: "Collaborate on projects that matter" },
      { id: "land-community", label: "Build or find land-based community" },
      { id: "network", label: "Network with aligned entrepreneurs" },
      { id: "events", label: "Attend transformational events and retreats" },
      { id: "build-ecosystem", label: "Help build the ecosystem/platform" },
    ],
  },
  // 8. Give & Receive (merged gift + seek)
  {
    id: "give-receive",
    type: "give-receive",
    title: "Give & Receive",
    subtitle: "What you bring, and what you're looking for",
    field: "uniqueGift",
    extraFields: ["receiveFromCommunity"],
    required: true,
  },
  // 9. Found Us
  {
    id: "found-us",
    type: "single-select",
    title: "How did you find us?",
    field: "howFoundUs",
    hasOther: true,
    otherPlaceholder: "Please specify...",
    otherField: "howFoundUsOther",
    detailField: "howFoundUsDetail",
    detailOptions: {
      invitation: "From whom?",
      social: "Which platform?",
      event: "Which event?",
    },
    required: true,
    options: [
      { id: "invitation", label: "Personal invitation or recommendation" },
      { id: "social", label: "Social media" },
      { id: "event", label: "Event" },
      { id: "search", label: "Web search" },
      { id: "word-of-mouth", label: "Word of mouth" },
    ],
  },
  // 10. Engage
  {
    id: "engage",
    type: "multi-select",
    title: "How do you want to engage?",
    subtitle: "Select all that apply",
    field: "engagementStyles",
    required: true,
    options: [
      { id: "attend-events", label: "Attend future events" },
      { id: "facilitate", label: "Facilitate workshops/experiences" },
      { id: "collaborate", label: "Collaborate on projects" },
      { id: "organize", label: "Help organize/produce events" },
      { id: "contribute-skills", label: "Contribute skills to the collective" },
      { id: "find-services", label: "Find services/collaborators" },
      { id: "experience", label: "Just here for the experience" },
    ],
  },
  // 11. Preferences (with opt-ins merged in)
  {
    id: "preferences",
    type: "preferences",
    title: "Your preferences",
    subtitle: "Privacy, communication, and a couple final questions",
    field: "profileVisibility",
    extraFields: ["communicationPrefs", "aiPhoneCallOptIn", "marketingOptIn"],
    required: true,
    options: [
      { id: "public", label: "Public to all members" },
      { id: "searchable", label: "Searchable, contact requires permission" },
      { id: "private", label: "Private — admin introductions only" },
    ],
  },
  // 12. Review
  {
    id: "review",
    type: "review",
    title: "Looking good!",
    subtitle: "Review your answers and submit",
    field: "",
  },
];
